[
    "Overview",
    "Enchanting Procedure",
    "Tool Enchantments",
    "Efficiency",
    "Speed Bonus",
    "Fortune",
    "Silk Touch",
    "Unbreaking",
    "Sword Enchantments",
    "Bane of Arthropods",
    "Fire Aspect",
    "Knockback",
    "Looting",
    "Sharpness",
    "Smite",
    "Sweeping Edge",
    "Unbreaking",
    "Bow Enchantments",
    "Flame",
    "Infinity",
    "Power",
    "Punch",
    "Unbreaking",
    "Crossbow Enchantments",
    "Multishot",
    "Quick Charge",
    "Piercing",
    "Unbreaking",
    "Armor Enchantments",
    "Aqua Affinity (Helmet Only)",
    "Blast Protection",
    "Depth Strider (Boots Only)",
    "Feather Falling (Boots Only)",
    "Fire Protection",
    "Frost Walker (Boots Only)",
    "Projectile Protection",
    "Protection",
    "Respiration (Helmet Only)",
    "Soul Speed\xa0(Boots Only)",
    "Thorns",
    "Curse of Binding",
    "Curse of Vanishing",
    "Fishing Rod Enchantments",
    "Lure",
    "Luck of the Sea",
    "Trident Enchantments",
    "Impaling",
    "Riptide",
    "Loyalty",
    "Channeling",
    "Shield Enchantments",
    "Unbreaking",
    "Carrot On A Stick Enchantments",
    "Unbreaking",
    "Other Enchantments",
    "Mending",
    "Not Yet Released Enchantments",
    "Cleaving",
    "Enchantment Weight",
    "Gallery",
    "Videos",
]
