[
    "100 × 50\n",
    "Neutral (if no player-built)Passive (if player-built, and/or in Peaceful difficulty)\n",
    "To mobs: 7.5 × 3.75 to 21.5 × 10.75 To Enderman:12 × 6 to 16.5 × 8.25\nTo players:\n",
    "In Java Edition:\nHeight: 2.7 BlocksWidth: 1.4 Blocks\n",
    "In Bedrock Edition:\nHeight: 2.9 BlocksWidth: 1.4 Blocks\n",
    "0.25\n",
    "1.0\n",
    "An iron golem is a large, strong, neutral utility mob that defends players and villagers.\n",
    'In Java Edition, villagers can summon iron golems, either when they are gossiping or panicking. When a villager tries to summon a golem, up to 10 attempts are made to spawn a golem within a 16x13x16 box centered on the block the villager is standing on (block position +8/-8 blocks along x/z axes and +6/-6 blocks along y axis). A random y column is picked and then the topmost block and directly under the sky in that column is selected that is air, water, or lava, and has a "solid-blocking" block underneath, or block at y=+6 if none such is available in that column is selected. The target location is then checked whether the block underneath has a solid top surface (which is not the same as "solid-blocking"). The target block and 2 blocks above must not be a full block, be redstone-powered nor be rails, and the two blocks above must not be water. This means the iron golem can spawn inside 1-deep water or inside blocks like half-slabs, fences, and carpets (if other checks pass). Adjacent blocks are relevant, so golems do spawn partially inside adjacent solid blocks.[1] However, the spawning iron golem still must not collide with any existing entities.\n',
    "In Bedrock Edition, an iron golem can spawn naturally when a village first generates in the world. Iron golems also spawn in villages having at least 20 beds and 10 villagers, in a 16×6×16 volume around the village center defined by a bed, a bell, or another meeting point. In order for a village to spawn iron golems, 75% of the villagers in the village must have worked in the past day, 100% of the villagers must be linked to a bed, and a player must be within 80 blocks of the village horizontally and within 44 blocks vertically. The chance of attempting a spawn is 1⁄700 per game tick, which averages to one spawn attempt every 35 seconds. Iron golems can spawn provided the 2 x 4 x 2 space above the spawn point (that is, horizontally centered on the NW corner of the block it spawns on) contains only non-solid blocks, and the block it spawns on is solid.\n",
    "Iron golems are created by placing four iron blocks in a T shape (as shown in the image), and then placing a carved pumpkin, jack o'lantern or pumpkin\u200c[BE only] on top of the center upper block. The pumpkin may be placed by the player, a dispenser or an enderman, but it must be placed last. It needs space around it to be able to spawn and cannot spawn in a confined area. Alternatively, the blocks can be placed in any order with an uncarved pumpkin; the player can shear the pumpkin to spawn the golem. When successfully transformed, it is naturally passive towards all players under all circumstances. It can, however, attack the player’s tamed wolves, if punched accidentally, but it never directly attacks the player.\n",
    "The block arrangement can be placed upright, lying down, or upside-down. The four empty spaces in the diagram (above and below each of the arms) must be air blocks. Any non-air block (including blocks such as snow layers, tall grass, and water) present in any of the empty spaces prevent the golem from spawning.\n",
    "Like other constructed mobs, iron golems always spawn facing south. Their large size may cause them to take suffocation damage from nearby solid blocks at the level of their head.\n",
    "Iron golems can also be found surrounding pillager outposts, confined inside dark oak cages. When freed, they can help the player by attacking any nearby pillagers.\n",
    "Iron golems drop when they die:\n",
    "The Looting enchantment is ineffective against iron golems as it does not give any extra iron ingots or poppies when killed.\n",
    "Iron golems wander around a village in a patrol-like fashion, staying close to the edges of buildings and other structures. Like villagers, iron golems do not wander away from a village, regardless of how they were spawned. An iron golem sometimes faces a villager as if they are speaking to each other. Iron golems are able to spawn poppies in their hands and offer them to villagers, symbolizing the friendly relationship between the villagers and golems.\n",
    "If not within a village, iron golems slowly wander around, usually making their way to a nearby village.\n",
    "Iron golems can walk up a full block height without jumping and walk over a 1 block wide hole without falling in. They avoid water, lava, fire and cacti. Iron golems are immune to both drowning and fall damage. When in water, they sink, but can still move freely when in and underwater. \n",
    "In Java Edition, when they're at 3/4 of full health, iron golems start to crack. An iron golem can be healed when the player right-clicks the chest of the iron golem with an iron ingot.\n",
    "Like all utility mobs, iron golems can be leashed.\nIron golems move faster in Bedrock Edition. \n",
    "Iron golems are aggressive to most hostile or neutral mobs (list below) within 16 blocks of them, although they are not effective on flying mobs (ender dragon, wither, phantom, ghast) that don't venture into the iron golem's reach. If a player has -15 popularity or less, any village naturally-spawned iron golems become forever hostile to that player. Naturally, they retaliate when attacked by a mob. Iron golems built by a player never attack them. Although they are guardians of villages, iron golems aren't actually provoked when a villager nearby is attacked by a mob. This does not apply to players, who will be met with hostility when attacking a villager near an iron golem. Iron golems never attack each other.\n",
    "When attacking, an iron golem moves quickly toward its target and swing its arms up violently to attack, dealing 7 to 21 × 10.5 damage and flinging the target into the air. Iron golems have a comparatively large attack range, allowing them to attack through a solid 1 block thick wall, even without a line of sight to the target. \n",
    "It is possible for multiple golems to simultaneously hit the same target. The height to which the victim is sent flying is relative to the number of golems that attack it.\n",
    "The list below is complete. It contains all mobs including players. \n",
    "A baby zombie riding a chicken attacks iron golems.\nIf a baby zombified piglin is riding the chicken, the zombified piglin attacks the golem only after the golem attacks first.\nThe iron golem attacks the rider, not the chicken.\n",
    "A naturally-spawned iron golem or commands-spawned iron golem attacks the player if the player attacks it while playing in the adventure and survival modes (it does not attack the player in creative or spectator mode). \nAn iron golem can also attack any nearby player who has reduced popularity in a village.\nIron golems created by the player do not attack the player under any circumstances. The player also automatically attacks the golem with the Thorns enchantment.\n",
    "A naturally-spawned iron golem knows where raiding illager locations are from behind solid walls and from underground and attempts to move toward them. An iron golem created by the player or summoned by a command cannot detect raiders through obstructions.\n",
    "Zombies (and variants), zoglins, skeletons (and variants), spiders, cave spiders, slimes, magma cubes, withers, and illagers naturally attack iron golems on sight and may cause major damage, especially if the mobs attack in groups. If an iron golem is attacked by multiple mobs, it retaliates in the order it was attacked. In Bedrock Edition, silverfish and witches may naturally attack it too.\n",
    "Iron golems have 100% knockback resistance. However, they can be knocked back by the Knockback enchantment on swords and the Punch enchantment on bows.\n",
    "However, in Bedrock Edition, knockback seems to have no effect on iron golems.\n",
    "Iron golems have different stages of being cracked to show their health. When their health is above 74 × 37, some cracks are visible. When their health is between 50 × 25 and 74 × 37, a few more cracks appear. When their health is between 25 × 12.5 and 49 × 24.5, they appear more cracked. When their health is lower than 25 × 12.5, many cracks are visible.\n",
    "In Java Edition, using an iron ingot on an iron golem restores its health by 25%.[2]\n",
    'Like villagers, iron golems in Bedrock Edition use a strategy of pathfinding that prioritizes walking on certain "low-cost" blocks.\n',
    "Stone\nStone Bricks\nSandstone\nMossy Cobblestone\nSlabs\nPlanks\nBricks\nNether Bricks\nRed Nether Bricks\nEnd Stone Bricks\nRed Sandstone\nStained Glass\nGlass\nGlowstone\nPrismarine\nBlock of Emerald\nBlock of Diamond\nLapis Lazuli Block\nBlock of Gold\nBlock of Redstone\nGlazed Terracotta\n",
    "Lectern\nComposter\nGrindstone\nBlast Furnace\nSmoker\nFletching Table\nCartography Table\nBrewing Stand\nSmithing Table\nCauldron\nBarrel\nLoom\nStonecutter\n",
    "Java Edition:\n",
    "Bedrock Edition:\n",
    "Iron golems have entity data associated with them that contain various properties.\n",
    "\n",
    'Issues relating to "Iron Golem" are maintained on the bug tracker. Report issues there.\n',
    "An iron golem offers a villager a poppy.\n",
    "An iron golem offers a poppy to several villager children.\n",
    "An iron golem attacking a spider by throwing it into the air.\n",
    "An iron golem attacking the player.\n",
    "Spawn boundaries of the village, in case of a single house. If an iron golem exits these boundaries, it detaches from the village and a new one can spawn.\n",
    "Iron golems acting weirdly in a player-created village, by attempting to cross in a two-block-high gap.\n",
    "\n",
    "Entities",
]
