[
    "Common\n",
    "Yes\n",
    "Yes (64)\n",
    "Iron ingots are versatile metal ingots used extensively in crafting.\n",
    "Smelting iron ore in a furnace or blast furnace is the most common way to obtain iron ingots.\n",
    "Iron Ingot can be created from its base elements, using the compound creator.\u200c[Bedrock and Education editions only]\n",
    "Iron golems drop 3-5 iron ingots upon death, regardless of the way they die. The looting enchantment does not increase the amount of iron ingots dropped.\n",
    "Zombies, husks, and zombie villagers have a 2.5% chance of dropping either an iron ingot, carrot, or potato when killed by a player or tamed wolf. This is increased by 1% per level of looting. This gives iron ingots the following chances of dropping:\n",
    "Apprentice-level Armorer, Toolsmith, and Weaponsmith villagers buy 4 iron ingots for an emerald as their third trade.\u200c[Bedrock Edition only]\n",
    "Apprentice-level Armorer villagers have a 50% chance to buy 4 iron ingots for one emerald, and apprentice-level Toolsmith and Weaponsmith villagers always offer to buy 4 iron ingots for one emerald.\u200c[Java Edition only]\n",
    "Iron ingots are the repair items for the iron tier and chainmail and iron armor materials, and thus can be used to repair the following items in an anvil:\n",
    "In Java Edition, using an iron ingot on an iron golem restores its health by 25 × 12.5.\n",
    "Iron ingots can be used to select powers from a beacon. The player must select one of the available powers, and then insert an ingot in the item slot. \n",
    "An iron ingot can be substituted for an emerald, a gold ingot, a diamond, or a netherite ingot.\n",
    "\n",
    "Java Edition:\n",
    "Bedrock Edition:\n",
    'Issues relating to "Iron Ingot" are maintained on the bug tracker. Report issues there.\n',
    "Items",
]
