[
    "Yes\n",
    "Yes (64)\n",
    "\n",
    "1\n",
    "1\n",
    "No\n",
    "Partial (blocks light)\n",
    "No\n",
    "No\n",
    "A pumpkin is a fruit block that appears in patches of grassy biomes. Pumpkins have the same texture on all 4 sides.\n",
    "A carved pumpkin is a carved version of a pumpkin that can be worn or used to spawn golems. It can be made by using shears on a pumpkin placed in the world. \n",
    "Pumpkins naturally generate with the terrain in most biomes in the Overworld, requiring only a grass block with air above (clear of any plants such as flowers or grass) and can generate whether or not that grass block has a layer of snow cover. Practically speaking, this means that the occurrence of pumpkins in stony or sandy biomes, or in grassy biomes with few clear grass blocks, is comparatively rare.\n",
    "Pumpkins naturally generate in stem farm rooms in woodland mansions.\n",
    "4 pumpkins generate naturally in woolen tents in pillager outposts.\n",
    "Pumpkins generate naturally in taiga and snowy taiga villages, changing the hay bales to pumpkins.\n",
    "Carved pumpkins generate in rail rooms in woodland mansions.\n",
    "Carved pumpkins also generate in pillager outposts as a part of scarecrows.\n",
    "Pumpkins can be mined with anything, but axes are the quickest.\n",
    "When a pumpkin is pushed by a piston, it breaks and drops as an item.\n",
    "Zombies, zombie villagers, skeletons, wither skeletons, drowned, husks, strays, and zombified piglins have a chance of wearing a carved pumpkin if they spawn during Halloween (October 31). If a mob wearing a carved pumpkin is killed using a tool enchanted with Looting, there is a chance equivalent to the level of Looting used to drop the carved pumpkin, up to a maximum of a 3% chance of a drop.\n",
    "Wandering traders can sell a pumpkin for one emerald.\n",
    "A carved pumpkin (and 4 pumpkin seeds in Java Edition or 1 unit of pumpkin seeds in Bedrock Edition) is obtained by using shears on an uncarved pumpkin. Once carved, a pumpkin cannot be changed back to uncarved. This changes the rotation of the top texture.[1]\n",
    "When placed, a carved pumpkin automatically faces the player.\n",
    "Pumpkin farming strategies parallel those of melons. Planted pumpkin seeds grow a central stem that, after maturing, generates pumpkins randomly on adjacent vacant dirt/grass/farmland/podzol/coarse dirt. If a pumpkin is harvested without also cutting the central stalk, another pumpkin generates afterward without requiring replanting or waiting for the stalk to mature again. If a carved pumpkin is desired, simply use the shears on the pumpkin on the ground, and then harvest it as normal.\n",
    "Pumpkin stems take around 10 to 30 minutes to fully develop. They require a light level of 9 or higher to grow. Bone meal can be used on pumpkin stems to become fully-grown, but this does not produce a pumpkin immediately.\n",
    "A carved pumpkin can be equipped as a helmet without any actual armor value. It functions as a mask that allows the player to look at endermen without provoking an attack. When worn, it limits the player's viewing area to a mask pattern that resembles the pumpkin's carved face. The pattern does not appear in third person view, or via F1 key.\n",
    "Dispensers can equip a carved pumpkin on a player, mob or armor stand with an empty helmet slot, within the block the dispenser is facing.\n",
    "Carved pumpkins can be used to make snow golems and iron golems as shown below. Snow golems require snow blocks for their bodies, while iron golems require iron blocks. The carved pumpkin must be placed last or the golem does not spawn. The orientation of the carved pumpkin does not matter while building an iron golem or snow golem. Iron golems cannot be built in water.\n",
    "Apprentice-level Farmer villagers buy 6 pumpkins for an emerald as part of their trades.\u200c[Bedrock Edition only]\n",
    "Apprentice-level Farmer villagers have a 2⁄3 chance to buy 6 pumpkins for one emerald.\u200c[Java Edition only]\n",
    "Carved Pumpkins can receive the following enchantments, but only through an anvil.\n",
    "Placing a pumpkin or carved pumpkin into a composter has a 65% chance of raising the compost level by 1.\n",
    "Pumpkin can be placed under note blocks to produce didgeridoo sounds.\n",
    "Java Edition:\n",
    "Java Edition:\n",
    "Bedrock Edition:\n",
    "In Bedrock Edition, carved pumpkins use the following data values:\n",
    "Java Edition:\nCarved pumpkin:\n",
    "Bedrock Edition:\n",
    "\n",
    "A group of carved pumpkins.\n",
    "A player wearing a carved pumpkin as a helmet.\n",
    "View of the world while wearing a carved pumpkin as a helmet.\n",
    "A screenshot of a pumpkin on a stem in Beta 1.8 pre-release.[n 1]\n",
    "Looking at an enderman while wearing a carved pumpkin as a helmet. Notice that its back is turned and it's not attacking the player.\n",
    "A floating pumpkin due to ponds being generated after the rest of the terrain.[n 1]\n",
    "A zombie and a skeleton wearing a jack o'lantern and a carved pumpkin, respectively, on the date of Halloween.\n",
    "A naturally generated carved pumpkin in a woodland mansion room.\n",
    "Due to a glitch, this baby zombie wearing a carved pumpkin renders as if the carved pumpkin is floating above its head.\n",
    "A group of pumpkins generated in a snowy tundra.\n",
    "Blocks",
]
