[
    "300 × 150\u200c[JE only]600 × 300\u200c[BE only]\n",
    "4\xa0()\n",
    "Hostile\n",
    "Birth Explosion:\nVaries by proximity; maximum:\nEasy: 49 × 24.5Normal: 96 × 48Hard: 144 × 72\n\nWither Skull:\nEasy: 5\nNormal: 8 + Wither II for 10 seconds (1 per sec) \nHard: 12 × 6 + Wither II for 40 seconds (1 per sec)\nDash Attack\u200c[BE only]\n15 × 7.5\n",
    "In Java Edition:\nHeight: 3.5 BlocksWidth: 0.9 Blocks\n",
    "In Bedrock Edition:\nHeight: 3.0 BlocksWidth: 1.0 Blocks\n",
    "Built by player; 10 second spawn delay.\n",
    "The wither is an undead hostile boss mob that floats and shoots explosive skulls at players and mobs. It is currently the only player-made hostile mob in the game.\n",
    "The fight varies across editions; the Bedrock wither has twice as much health and different attacks than its Java counterpart.\n",
    "The wither drops 50 experience points and a nether star, a crafting ingredient for beacons.\n",
    "The wither is spawned by placing 4 blocks of Soul Sand and/or Soul Soil in a T shape (see top imageimage to the left), and putting 3 wither skeleton skulls on top of the three upper blocks. The last block placed must be one of the three skulls and can be placed by the player or a Dispenser. Air blocks are required on either side of the base soul sand or soul soil block under the upper blocks (non-solid blocks such as Grass and flowers prevent the wither from spawning). The building pattern can have any orientation (including horizontal and upside-down) as well as the skulls; the wither always spawns at the foot of the pattern. When the wither has successfully spawned, it is angered and creates an explosion around itself.\n",
    "Like other hostile mobs, the wither despawns when the difficulty is changed to Peaceful. The wither spawning structure also fails in Peaceful difficulty; the blocks simply do nothing.\n",
    "The wither always drops one Nether Star upon death. In Java Edition the dropped nether star takes ten minutes to despawn, twice as long as normal items. In Bedrock Edition the nether star never despawns. It cannot be destroyed by explosions, as all dropped nether stars are immune to them. The Looting enchantment does not increase this drop. It also drops 50 when killed by a player or a tamed wolf.\n",
    "When spawned, the wither grows larger in size as its health bar fills up. While in this state, the wither is invulnerable, and neither moves nor attacks. When this state ends (after 10 seconds), the wither creates a large explosion centered on itself, destroying nearby blocks and dealing up to 99 × 49.5 damage to nearby mobs/players. This explosion has a blast power of 7, more than that of a charged creeper or an end crystal. It is accompanied by a loud gruesome sound that can be heard equally from across the map and in all dimensions. After this, the wither attacks nearby mobs and can take damage.\n",
    "The wither is immune to fire, lava and drowning damage. Suffocation is usually ineffective because, upon taking damage, the wither breaks any block it touches. However, it cannot break bedrock, end gateway blocks, end portal blocks, end portal frames, command blocks, structure blocks, jigsaw blocks, barriers or moving pistons. Accordingly, it can be suffocated in the exit portal or end gateway, for example. Like other undead mobs, the wither is harmed by the Instant Health effect and healed by the Instant Damage effect as well as affected by weapons with the Smite enchantment. It is immune to all other status effects, like the ender dragon. \n",
    "The wither is hostile toward all mobs except:\n",
    "If the wither is idle, it simply hovers and is unable to gain altitude. On Normal or Hard difficulty, it fires blue skulls in random directions until it finds a target.\n",
    "The wither has a dark purple\u200c[Java Edition only] or pink\u200c[Bedrock Edition only] boss health bar that appears only when a player is looking in the wither's direction, including through walls. When looking at the wither, the world gets slightly darker. All withers display a boss bar on the screen. \n",
    "Upon noticing a mob, the wither hovers above it and rapidly shoots black wither skulls. Each head fires independently, allowing a wither to attack up to three different mobs/players at the same time. The main head controls the Wither's movement, and has a 0.1% chance to shoot a blue wither skull instead of the default black one.\n",
    "Whenever a wither kills another mob, a wither rose is either planted or dropped as an item at that mob's location; however, it may be destroyed by other wither skulls.\n",
    "The wither has a passive regeneration rate of 1 every 20 ticks (1 second), and a direct killing blow on a target instantly heals 5.\n",
    'When its health drops below half (150 × 75), the wither gains a natural "wither armor" effect, which makes it immune to damage from arrows and thrown tridents and causes it to fly at the same height as the player. The armor disappears if it regenerates above half health.\n',
    "Upon noticing a player or mob, the wither flies to a random location and hovers in place. It shoots 3 black wither skulls and one blue wither skull before flying to another location. On Normal difficulty or higher, if the wither has targeted an entity but cannot find a location to pathfind to, it will shoot random blue skulls in a random direction along with the skulls directed towards the target.\n",
    "At half health, it causes a large explosion that spawns 3–4 wither skeletons (except on Easy difficulty), as well as gaining wither armor. Instead of flying to a random location, it dashes toward its target, destroying blocks and damaging mobs in its path. It also fires up to 4 skulls per burst: three black skulls followed by one blue skull. It has different spawn and death animations, both of which involve the wither exploding. \nWither roses always drop as an item when the Wither kills a mob. The Wither rose inflicts the Wither effect when stepped on.[verify]\n",
    "The sky light level drops to 11 and dark clouds appear from the moment the wither spawns until it is dead, preventing zombies, skeletons, and drowneds from burning in sunlight.\n",
    "Height: 0.3125 BlocksWidth: 0.3125 Blocks\n",
    "JE: 66\n",
    "The wither rapidly fires explosive projectiles called wither skulls, which look like extra heads of itself, at its target. There are two types of wither skulls: a fast-moving black one, and a slower blue one. Black wither skulls explode with a blast power of 1, the same as a ghast's fireball, and cannot break blocks with a blast resistance above 4. The blue wither skull has the same explosion strength, but moves slower and treats all blocks except for a few \"unbreakable\" blocks as having a blast resistance of no more than 0.8, making it more destructive to the terrain. This means that blue wither skulls can break obsidian. This doesn't apply to unbreakable blocks, like bedrock or an end portal frame.\n",
    "If either type of wither skull hits a player or mob, it does 8 damage on Normal difficulty. It also inflicts Wither II for 10 seconds on Normal difficulty and 40 seconds on Hard, which turns the player's hearts black () and drains health, similarly to poison. However unlike poison, it can kill the player.\n",
    "Like other status effects, the wither effect can be cured by drinking milk.\n",
    "In Bedrock Edition, the blue skull can be deflected by hitting it with hand or throwable entities (similar to ghast fireballs).\n",
    "Java Edition:\n",
    "Bedrock Edition:\n",
    "Withers have entity data associated with them that contain various properties.\n",
    "Wither skulls have entity data associated with them that contain various properties.\n",
    "\n",
    "\n",
    "\n",
    'Issues relating to "Wither" are maintained on the bug tracker. Report issues there.\n',
    "The withering effect after being damaged by a Wither Skull.\n",
    'The "wither armor" that blocks arrows.\n',
    "The wither and its armor.\n",
    "A larger image to show how to summon the wither.\n",
    "The wither prepares for explosion with the invulnerable status after summoned.\n",
    "The pit created after the wither has charged.\n",
    "The wither attacking horses.\n",
    "Wither (texture)\n",
    "Wither boss Mobestiary\n",
    "Wither Storm, a variant of Wither as it appears on Minecraft: Story Mode.\n",
    "\n",
    "Entities",
]
